ntp_timezone: "America/New_York"
main_username: kp
system_username: jax

users:
  - {user: "{{ main_username }}", pass: "{{ main_user_pass}}"}
  - {user: "ansible", pass: "{{ ansible_user_pass}}"}

package_list:
  - name: bash-completion
  - name: ca-certificates
  - name: curl
  - name: git
  - name: gnupg2
  - name: htop
  - name: jq
  - name: ncdu
  - name: net-tools
  - name: python3
  - name: python3-apt
  - name: python3-pip
  - name: software-properties-common
  - name: tmux
  - name: wget

docker_users:
  - "{{ main_username }}"
  - "{{ system_username }}"
