---
- name: build hosts file
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
  become: yes

# ansible_hostname ansible_fqdn ansible_all_ipv6_addresses
