---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: vagrant-rhel-8
    image: ubi
    registry:
      url: registry.access.redhat.com/ubi8
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: False
provisioner:
  name: ansible
  extra_vars:
    ansible_python_interpreter: /usr/bin/python3
  log: True
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
