---
# vars file for docker

ubuntu_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

ubuntu_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

debian_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

debian_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
