---
# ansible-playbook -i localhost, playbook.yml -e 'ansible_python_interpreter=/usr/bin/python3'

- hosts: all
  connection: local
  become: yes
  gather_facts: yes
  roles:
    - role: packer
    - role: vagrant
    - role: virtualbox
    - role: kvm
    - role: docker
    # - role: podman
    # - role: lxd
    # - role: vmware
