roles:
  - src: ironicbadger.ansible_role_docker_compose_generator
  - src: caddy_ansible.caddy_ansible
  - src: grog.package
  - src: geerlingguy.docker
  - src: geerlingguy.ntp
  - src: geerlingguy.nfs
  - src: geerlingguy.pip
  - src: geerlingguy.samba
  - src: rossmcdonald.telegraf
  - src: ironicbadger.ansible_role_bash_aliases
  - src: ironicbadger.ansible_role_hddtemp
  - src: ironicbadger.ansible_role_proxmox_nag_removal
  - src: ironicbadger.ansible_users
  - src: weareinteractive.environment

collections:
  - community.general
  - community.docker
