---
- hosts: all
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'vars/vars.yml'
  tasks:
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
      when: ansible_distribution == 'Ubuntu'

- hosts: master
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'vars/vars.yml'
  roles:
    - role: ksp.master
    - role: grog.package
    - role: geerlingguy.pip
    - role: rossmcdonald.telegraf
    - role: geerlingguy.samba
    - role: geerlingguy.nfs
    - role: geerlingguy.ntp

- hosts: docker
  become: true
  tags:
    - docker
  roles:
    - role: "nickjj.docker"

- hosts: plexus
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'vars/vars.yml'
  roles:
    - role: ksp.plex

- hosts: hassio
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'vars/vars.yml'
  tasks:
    - name: copy loki config files
      ansible.builtin.copy:
        src: loki/
        dest: "{{ app_data_root }}/loki/"
        mode: "0755"
    - name: copy promtail config files
      ansible.builtin.copy:
        src: promtail/
        dest: "{{ app_data_root }}/promtail"
        mode: "0755"

  roles:
    - role: hadret.rsyslog
    - role: hadret.containers
