---
- hosts: all:!localhost
  tasks:
    - name: import keys from github
      authorized_key:
        user: "{{ ansible_user | default('kp') }}"
        state: present
        key: https://github.com/kprestel.keys
    - name: update all packages
      become: true
      package:
        name: '*'
        state: latest

- hosts: localhost
  tasks:
    - name: Upgrade the system using yay
      kewlfft.aur.aur:
        upgrade: yes
        use: yay
      become: true
      become_user: aur_builder
