---
# vars file for podman

centos_packages:
  - podman
  - buildah
  - skopeo

redhat_packages:
  - '@container-tools:1.0/common'
  - podman-docker

fedora_packages:
  - podman
  - buildah
  - skopeo
  - podman-docker

ubuntu_packages:
  - software-properties-common
  - uidmap
  - podman
  - buildah
  - skopeo
  - podman-docker
