ansible_become_password: "{{ vault_kp_password }}"
ansible_user: kp
ansible_python_interpreter: "/usr/bin/python3"
compose_file_path: "/home/kp/workspace/docker-compose.yml"
compose_env_file_path: "/home/kp/workspace/.env"