---
- name: Update pveam
  command: pveam update

- name: Download container templates
  command: pveam download local {{ item }}
  with_items:
    - ubuntu-20.04-standard_20.04-1_amd64.tar.gz
    - ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz

- name: Create LXCs
  proxmox:
    api_host: "{{ proxmox_ip }}"
    api_user: root@pam
    api_password: "{{ api_password }}"
    node: master
    vmid: "{{ item.vmid }}"
    hostname: "{{ item.hostname }}"
    ostemplate: "{{ item.os_template }}"
    cpus: "{{ item.cpus }}"
    cores: "{{ item.cores }}"
    cpuunits: "{{ item.cpu_units }}"
    swap: "{{ item.swap }}"
    memory: "{{ item.memory }}"
    disk: "{{ item.disk }}"
    storage: local-zfs
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip={{ item.ip }},firewall=true,bridge=vmbr0"}'
    onboot: "{{ item.onboot }}"
    unprivileged: "{{ item.unprivileged }}"
    pubkey: "{{ ssh_pubkey }}"
    state: present
    password: "{{ ansible_user_pass }}"
    features:
      - nesting={{ item.nesting }}
      - keyctl={{ item.keyctl }}
  loop:
    "{{ lxc_containers }}"

- name: Start lxc containers
  proxmox:
    api_host: "{{ proxmox_ip }}"
    api_user: root@pam
    api_password: "{{ api_password }}"
    node: master
    vmid: "{{ item.vmid }}"
    state: started
    timeout: 90
  loop:
    "{{ lxc_containers }}"
