---
- name: Install Proxmoxer
  pip:
    name: proxmoxer

# - name: Ensure user groups exists
#   group:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - "{{ main_username }}"
#     - "{{ system_username }}"
#     - ansible

- name: Add samba users
  user:
    name: samba
    password: "!"
    create_home: false

- name: Set up containers
  include: infra.yml
  # when: infrastructure == true

#   template:
#     src: smb.conf.j2
#     dest: /etc/samba/smb.conf
#     owner: root
#     group: root
# - name: Restart samba
#   service:
#     name: smbd
#     state: restarted
