---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: vmware-rhel-8
    box: cmihai/rhel-8-base
provisioner:
  name: ansible
  log: True
  extra_vars:
    ansible_python_interpreter: /usr/bin/python3
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
