---
# ansible-playbook -i localhost, playbook.yml

- name: setup a virtualization environment
  hosts: all
  connection: local
  become: yes
  gather_facts: yes
  roles:
    - role: crivetimihai.virtualization.kvm
      #    - role: crivetimihai.virtualization.lxd
      #    - role: crivetimihai.virtualization.vmware_workstation
    - role: crivetimihai.virtualization.virtualbox
      #    - role: crivetimihai.virtualization.podman
    - role: crivetimihai.virtualization.docker
    - role: crivetimihai.virtualization.vagrant
    - role: crivetimihai.virtualization.packer
