- name: "init"
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
    # TODO: check if debian
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest
        force_apt_get: true
      loop: ["aptitude"]
    - name: Install a list of packages
      apt:
        pkg: "{{ base_packages }}"
        update_cache: true
        state: latest
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Remove useless packages from the cache
      apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: true
